runtime: nodejs18
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 0.03s

handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\.(js|css|png|jpg|gif|svg|ico|txt|woff|woff2|ttf|eot|pdf))$
    static_files: dist/\1
    upload: dist/.*\.(js|css|png|jpg|gif|svg|ico|txt|woff|woff2|ttf|eot|pdf)$
    secure: always

  # Serve assets directory
  - url: /assets
    static_dir: dist/assets
    secure: always

  # Catch all handler to serve index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

env_variables:
  NODE_ENV: "production"

entrypoint: node server.cjs 